export const INIT_WEBSOCKET = 'INIT_WEBSOCKET'
export const SET_SID = 'SET_SID'
export const SET_USER = 'SET_USER'
export const SET_ISLOGIN = 'SET_ISLOGIN'
export const SET_MSG = 'SET_MSG'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_HIDE = 'SET_HIDE'
